<a href="https://colab.research.google.com/github/PaulFSherwood/python/blob/master/AI/TensorTest01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x  # this line is not required unless you are in a notebook
import tensorflow as tf  # now import the tensorflow module
print(tf.version)  # make sure the version is 2.x

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [2]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3, -1])

In [3]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [20]:
tensor5 = tf.random.uniform([2,8,8],minval=0, maxval=2, dtype=tf.int32)
print(tensor5)

tf.Tensor(
[[[0 0 0 1 0 1 0 1]
  [1 0 0 1 1 0 1 1]
  [1 1 0 1 1 0 0 0]
  [0 1 0 0 1 1 0 0]
  [1 0 0 0 1 1 0 1]
  [0 1 0 0 1 0 1 1]
  [1 1 1 1 0 0 1 0]
  [1 0 1 1 0 1 1 0]]

 [[1 0 0 0 1 1 1 1]
  [1 0 0 0 0 0 0 0]
  [0 0 1 0 0 1 0 0]
  [0 0 0 1 0 0 1 0]
  [0 1 0 0 1 0 0 0]
  [0 0 0 1 0 0 1 1]
  [0 0 1 1 1 0 0 1]
  [1 0 1 1 1 0 1 1]]], shape=(2, 8, 8), dtype=int32)
